on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Build and Release Web
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CYF_BOT_TOKEN }}
          cname: fafa-runner.chenyifaer.com
          publish_dir: ./out
